import { DataTypes, Model } from "sequelize";

export class FuelStation extends Model {}

export const FuelStationModel = {
  id: {
    type: DataTypes.STRING,
    primaryKey: true,
  },
  postalCode: DataTypes.STRING,
  address: DataTypes.STRING,
  openingHours: DataTypes.STRING,
  latitude: DataTypes.FLOAT,
  longitude: DataTypes.FLOAT,
  locality: DataTypes.STRING,
  margin: DataTypes.STRING,
  municipality: DataTypes.STRING,
  province: DataTypes.STRING,
  referral: DataTypes.STRING,
  signage: DataTypes.STRING,
  saleType: DataTypes.STRING,
  percBioEthanol: DataTypes.STRING,
  percMethylEster: DataTypes.STRING,
  municipalityId: DataTypes.INTEGER,
  provinceId: DataTypes.INTEGER,
  regionId: DataTypes.INTEGER,
  biodieselPrice: DataTypes.FLOAT,
  bioethanolPrice: DataTypes.FLOAT,
  CNGPrice: DataTypes.FLOAT,
  LNGPrice: DataTypes.FLOAT,
  LPGPrice: DataTypes.FLOAT,
  gasoilAPrice: DataTypes.FLOAT,
  gasoilBPrice: DataTypes.FLOAT,
  premiumGasoilPrice: DataTypes.FLOAT,
  gasoline95E10Price: DataTypes.FLOAT,
  gasoline95E5Price: DataTypes.FLOAT,
  gasoline95E5PremiumPrice: DataTypes.FLOAT,
  gasoline98E10Price: DataTypes.FLOAT,
  gasoline98E5Price: DataTypes.FLOAT,
  hydrogenPrice: DataTypes.FLOAT,
}