import { DataTypes, Model } from "sequelize";
import { FuelStation } from "../entities/FuelStation.model";

export class FuelStationsTable extends Model<FuelStation> {}

export const FuelStationModel = {
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
  },
  stationId: DataTypes.STRING,
  postalCode: DataTypes.STRING,
  address: DataTypes.STRING,
  openingHours: DataTypes.STRING,
  latitude: DataTypes.FLOAT,
  longitude: DataTypes.FLOAT,
  locality: DataTypes.STRING,
  margin: DataTypes.STRING,
  municipality: DataTypes.STRING,
  province: DataTypes.STRING,
  referral: DataTypes.STRING,
  signage: DataTypes.STRING,
  saleType: DataTypes.STRING,
  percBioEthanol: DataTypes.STRING,
  percMethylEster: DataTypes.STRING,
  municipalityId: DataTypes.INTEGER,
  provinceId: DataTypes.INTEGER,
  regionId: DataTypes.INTEGER,
  adbluePrice: DataTypes.FLOAT,
  ammoniaPrice: DataTypes.FLOAT,
  biodieselPrice: DataTypes.FLOAT,
  bioethanolPrice: DataTypes.FLOAT,
  compressedBiogasPrice: DataTypes.FLOAT,
  liquefiedBiogasPrice: DataTypes.FLOAT,
  renewableDieselPrice: DataTypes.FLOAT,
  cngPrice: DataTypes.FLOAT,
  lngPrice: DataTypes.FLOAT,
  lpgPrice: DataTypes.FLOAT,
  gasoilAPrice: DataTypes.FLOAT,
  gasoilBPrice: DataTypes.FLOAT,
  premiumGasoilPrice: DataTypes.FLOAT,
  gasoline95E10Price: DataTypes.FLOAT,
  gasoline95E25Price: DataTypes.FLOAT,
  gasoline95E5Price: DataTypes.FLOAT,
  gasoline95E5PremiumPrice: DataTypes.FLOAT,
  gasoline95E85Price: DataTypes.FLOAT,
  gasoline98E10Price: DataTypes.FLOAT,
  gasoline98E5Price: DataTypes.FLOAT,
  renewableGasolinePrice: DataTypes.FLOAT,
  hydrogenPrice: DataTypes.FLOAT,
  methanolPrice: DataTypes.FLOAT,
}