name: Deploy Image to GHCR

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: "Build and push Docker image"
        run: |
          docker build . --tag ghcr.io/JGeek00/fuel-stations-spain-api:latest
          docker push ghcr.io/JGeek00/fuel-stations-spain-api:latest
